### PR TITLE
Tested learnbotDSL files

### PR DESCRIPTION
**Pull request by Aniq55**
## What changes were proposed in this pull request?
* changed the automation scripts
* generated the python code for the learnbotDSL test files within `event_tests` folder
* tested the generated code in simulator

### CODE REVIEW

**Comment by pilarbachiller** [comment]
Generated files should not be stored in the repository

**Comment by Aniq55** [comment]
@pilarbachiller  where should they be stored then?

**Comment by pilarbachiller** [comment]
They must be generated and stored locally.

**Comment by Aniq55** [comment]
alright!

**Pull request closed without merging**
