### PR TITLE
Moved all test files inside one folder

### PR DESCRIPTION
**Pull request by Aniq55**
## What changes were proposed in this pull request?
Addresses #50

### CODE REVIEW

**Comment by Aniq55** [comment]
It is not necessary that the `event_tests` folder remain inside the repository directory, it may be anywhere on the drive.

**Comment by pilarbachiller** [comment]
It must remain in the repository as any other test file. The generated files should be removed as we previously discussed.

**Comment by Aniq55** [comment]
@pilarbachiller 
`learnbot_create` creates the .py file
`learnbot_run` runs the created .py file
When do I delete the generated .py files? At the end of `learnbot_run` ?

**Comment by pilarbachiller** [comment]
No, what I mean is that they should not be stored in the repository

**Comment by Aniq55** [comment]
okay, got it.

**Comment by Aniq55** [comment]
@pilarbachiller please check now.

**Pull request merged**
